CREATE TABLE `products` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`brand` varchar(100) NOT NULL,
	`category` varchar(100) NOT NULL,
	`price` decimal(10,2) NOT NULL,
	`originalPrice` decimal(10,2),
	`image` varchar(500) NOT NULL,
	`images` json,
	`rating` decimal(3,2) NOT NULL DEFAULT '0.00',
	`reviews` int NOT NULL DEFAULT 0,
	`badge` varchar(50),
	`inStock` boolean NOT NULL DEFAULT true,
	`stockCount` int DEFAULT 0,
	`description` text NOT NULL,
	`features` json,
	`specifications` json,
	`colors` json,
	`variants` json,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`)
);
